baseURL = "http://tim.moor.kiwi/"
languageCode = "en-us"
title = "Tim Moor | Open Source Ninja"
theme = "hugo-resume-template"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Mr. Hugo"
    description = "My awesome description"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "TIM MOOR"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "TIM MOOR"
        subtitle = "Cloud Architect - Platform/Automation Specialist"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Experience"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Service"
            buttontext = "Close"


    [params.about]
        title = "About"

        mainText = "Technical Evangelist, Propeller Head, Super Geek and Open Source Ninja are just some of the names I been called. I like to think these terms of endearment are used when someone is highly motivated, confident and passionate about their craft. The following resume will endeavor to demonstrate that I am a highly motivated, confident and conscientious individual with a proven track record of acheivement and success. I am looking to leverage the skills and experience of the last 10 years to solve enable success in your orgnaisation."

        [params.about.button]
            text = "Download CV"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"

    [params.blog]
        title = "Blog"

    [params.contact]
        title = "Contact"


    [params.footer]
        copyright = "Copyright Â© Mobius Design Studio 2017"

        [params.footer.location]
            title = "CALL TIM"
            # Postal address (add as many lines as necessary)
            phone = "022 1004707"

        [params.footer.social]
            title = "GET SOCIAL"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-facebook"
                link = "https://www.facebook.com/tim.moor"

            [[params.footer.social.networks]]
                icon = "fa-google-plus"
                link=  "https://plus.google.com/u/0/+TimMoor"

            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "#"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "https://twitter.com/moor_kiwis#"

            [[params.footer.social.networks]]
                icon = "fa-github"
                link=  "https://github.com/moortimis#"


        [params.footer.credits]
            title = "SEND AN EMAIL"
            email = "tim.moor@linux-geek.co.nz"
